import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import { join } from 'path';
import { initTaskFile } from '../../../src/lib/services/task-service.js';

const TEST_DIR = join(process.cwd(), 'test-temp');
const TEST_FILE = join(TEST_DIR, 'test-init.md');

describe('Init Command Integration', () => {
    beforeEach(async () => {
        try {
            await fs.mkdir(TEST_DIR, { recursive: true });
        } catch {
            // Ignore
        }
    });

    afterEach(async () => {
        try {
            await fs.unlink(TEST_FILE);
        } catch {
            // Ignore
        }
    });

    it('should create file with all fixed sections', async () => {
        await initTaskFile(TEST_FILE);
        const content = await fs.readFile(TEST_FILE, 'utf-8');

        expect(content).toContain('# Tasks');
        expect(content).toContain('For AI agents: Do not edit this file by hand.');
        expect(content).toContain('markit -h');
        expect(content).toContain('## backlog');
        expect(content).toContain('## todo');
        expect(content).toContain('## progress');
        expect(content).toContain('## closed');
    });

    it('should create sections in correct order', async () => {
        await initTaskFile(TEST_FILE);
        const content = await fs.readFile(TEST_FILE, 'utf-8');
        const lines = content.split('\n');

        const backlogIndex = lines.findIndex(l => l.includes('## backlog'));
        const todoIndex = lines.findIndex(l => l.includes('## todo'));
        const progressIndex = lines.findIndex(l => l.includes('## progress'));
        const closedIndex = lines.findIndex(l => l.includes('## closed'));

        expect(backlogIndex).toBeLessThan(todoIndex);
        expect(todoIndex).toBeLessThan(progressIndex);
        expect(progressIndex).toBeLessThan(closedIndex);
    });
});
