import { Task, TaskData, FIXED_SECTIONS } from './task.js';

// Short note for AI agents so they use the CLI instead of editing this file by hand.
const AGENT_INSTRUCTIONS = [
    '<!--',
    'For AI agents: Do not edit this file by hand.',
    'Use the `markit` CLI to manage tasks instead.',
    'Run `markit -h` for instructions.',
    '-->',
];

function formatHeader(): string[] {
    return ['# Tasks', '', ...AGENT_INSTRUCTIONS, ''];
}

export function formatMarkdown(data: TaskData): string {
    const lines: string[] = [];
    lines.push(...formatHeader());

    for (const section of FIXED_SECTIONS) {
        const sectionTasks = data.tasks.filter(task => task.section === section);
        lines.push(`## ${section}`);

        if (sectionTasks.length === 0) {
            lines.push('');
        } else {
            const sortedTasks = [...sectionTasks].sort((a, b) => a.idNumber - b.idNumber);
            for (const task of sortedTasks) {
                lines.push(formatTaskLine(task));
            }
            lines.push('');
        }
    }

    return lines.join('\n');
}

function formatTaskLine(task: Task): string {
    const parts: string[] = [];
    const checkbox = task.checked ? '[x]' : '[ ]';
    parts.push(`- ${checkbox}`);
    const idString = String(task.idNumber).padStart(3, '0');
    parts.push(`id:${idString}`);

    // Description already contains tags and mentions inline, so use it as-is
    parts.push(task.description);

    // Add due date after description
    if (task.dueDate) {
        parts.push(`due:${task.dueDate}`);
    }

    return parts.join(' ');
}

export function formatEmptyFile(): string {
    const lines: string[] = [];
    lines.push(...formatHeader());

    for (const section of FIXED_SECTIONS) {
        lines.push(`## ${section}`);
        lines.push('');
    }

    return lines.join('\n');
}
