import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { promises as fs } from 'fs';
import { join } from 'path';
import {
    initTaskFile,
    addTask,
    editTask,
    moveTask,
    markDone,
    markWontdo,
    removeTask,
    listTasks,
    loadTasks,
    cleanTaskFile,
} from '../../src/lib/services/task-service.js';
import { SAMPLE_TODO_MD } from '../helpers/test-utils.js';

const TEST_DIR = join(process.cwd(), 'test-temp');
const TEST_FILE = join(TEST_DIR, 'test-todo.md');

describe('Task Service', () => {
    beforeEach(async () => {
        // Create test directory
        try {
            await fs.mkdir(TEST_DIR, { recursive: true });
        } catch {
            // Ignore if exists
        }
    });

    afterEach(async () => {
        // Cleanup test files
        try {
            await fs.unlink(TEST_FILE);
        } catch {
            // Ignore if doesn't exist
        }
    });

    describe('initTaskFile', () => {
        it('should create new file with empty sections', async () => {
            await initTaskFile(TEST_FILE);
            const content = await fs.readFile(TEST_FILE, 'utf-8');
            expect(content).toContain('# Tasks');
            expect(content).toContain('For AI agents: Do not edit this file by hand.');
            expect(content).toContain('markit -h');
            expect(content).toContain('## backlog');
            expect(content).toContain('## todo');
            expect(content).toContain('## progress');
            expect(content).toContain('## closed');
        });

        it('should throw error if file exists', async () => {
            await initTaskFile(TEST_FILE);
            await expect(initTaskFile(TEST_FILE)).rejects.toThrow('File already exists');
        });
    });

    describe('addTask', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
        });

        it('should add task to backlog', async () => {
            const task = await addTask(TEST_FILE, 'Test task');
            expect(task.description).toBe('Test task');
            expect(task.section).toBe('backlog');
            expect(task.id).toBe('001');
            expect(task.idNumber).toBe(1);
        });

        it('should increment ID for subsequent tasks', async () => {
            await addTask(TEST_FILE, 'Task 1');
            const task2 = await addTask(TEST_FILE, 'Task 2');
            expect(task2.id).toBe('002');
            expect(task2.idNumber).toBe(2);
        });
    });

    describe('editTask', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Original description');
        });

        it('should replace task description', async () => {
            const task = await editTask(TEST_FILE, '001', 'Updated description');
            expect(task.description).toBe('Updated description');

            const tasks = await listTasks(TEST_FILE);
            expect(tasks[0].description).toBe('Updated description');
            expect(tasks[0].section).toBe('backlog');
        });

        it('should update tags, mentions, and due date from new description', async () => {
            await editTask(TEST_FILE, '001', 'Rewrite docs #docs @ziao due:2025-06-01');
            const tasks = await listTasks(TEST_FILE);
            const task = tasks[0];

            expect(task.description).toBe('Rewrite docs #docs @ziao');
            expect(task.tags).toEqual(['docs']);
            expect(task.mentions).toEqual(['ziao']);
            expect(task.dueDate).toBe('2025-06-01');
        });

        it('should clear due date when omitted from new description', async () => {
            await editTask(TEST_FILE, '001', 'With due due:2025-06-01');
            await editTask(TEST_FILE, '001', 'Without due');
            const tasks = await listTasks(TEST_FILE);

            expect(tasks[0].description).toBe('Without due');
            expect(tasks[0].dueDate).toBeUndefined();
        });

        it('should throw error for empty description', async () => {
            await expect(editTask(TEST_FILE, '001', '   ')).rejects.toThrow('Description cannot be empty');
        });

        it('should throw error if task not found', async () => {
            await expect(editTask(TEST_FILE, '999', 'Nope')).rejects.toThrow('not found');
        });
    });

    describe('moveTask', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Test task');
        });

        it('should move task to different section', async () => {
            await moveTask(TEST_FILE, '001', 'todo');
            const tasks = await listTasks(TEST_FILE);
            expect(tasks[0].section).toBe('todo');
        });

        it('should throw error for invalid section', async () => {
            await expect(moveTask(TEST_FILE, '001', 'invalid')).rejects.toThrow('Invalid section');
        });
    });

    describe('markDone', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Test task');
        });

        it('should mark task as done and move to closed', async () => {
            await markDone(TEST_FILE, '001');
            const tasks = await listTasks(TEST_FILE);
            const task = tasks[0];
            expect(task.section).toBe('closed');
            expect(task.checked).toBe(true);
            // doneDate removed - no longer set
        });
    });

    describe('markWontdo', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Test task');
        });

        it('should mark task as wontdo and move to closed', async () => {
            await markWontdo(TEST_FILE, '001');
            const tasks = await listTasks(TEST_FILE);
            const task = tasks[0];
            expect(task.section).toBe('closed');
            expect(task.checked).toBe(false);
            // doneDate removed - no longer used
        });
    });

    describe('removeTask', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Task 1');
            await addTask(TEST_FILE, 'Task 2');
        });

        it('should remove task from file', async () => {
            await removeTask(TEST_FILE, '001');
            const tasks = await listTasks(TEST_FILE);
            expect(tasks).toHaveLength(1);
            expect(tasks[0].id).toBe('002');
        });
    });

    describe('listTasks', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Backlog task');
            await addTask(TEST_FILE, 'Another backlog task');
            await moveTask(TEST_FILE, '001', 'todo');
        });

        it('should list all tasks', async () => {
            const tasks = await listTasks(TEST_FILE);
            expect(tasks).toHaveLength(2);
        });

        it('should filter by section', async () => {
            const backlogTasks = await listTasks(TEST_FILE, 'backlog');
            expect(backlogTasks).toHaveLength(1);
            expect(backlogTasks[0].section).toBe('backlog');
        });

        it('should throw error for invalid section', async () => {
            await expect(listTasks(TEST_FILE, 'invalid' as any)).rejects.toThrow('Invalid section');
        });
    });

    describe('cleanTaskFile', () => {
        it('should reformat file and sort tasks by ID within sections', async () => {
            // Intentionally out-of-order tasks and messy spacing
            await fs.writeFile(
                TEST_FILE,
                `# Tasks

## closed
- [x] id:002 Done task

## backlog
- [ ] id:003 Third task
- [ ] id:001 First task

## todo

## progress
`,
                'utf-8'
            );

            await cleanTaskFile(TEST_FILE);
            const content = await fs.readFile(TEST_FILE, 'utf-8');
            const lines = content.split('\n');

            const backlogIndex = lines.findIndex(l => l.includes('## backlog'));
            const todoIndex = lines.findIndex(l => l.includes('## todo'));
            const progressIndex = lines.findIndex(l => l.includes('## progress'));
            const closedIndex = lines.findIndex(l => l.includes('## closed'));

            expect(backlogIndex).toBeLessThan(todoIndex);
            expect(todoIndex).toBeLessThan(progressIndex);
            expect(progressIndex).toBeLessThan(closedIndex);

            const taskLines = lines.filter(l => l.includes('id:'));
            expect(taskLines[0]).toContain('id:001');
            expect(taskLines[1]).toContain('id:003');
            expect(taskLines[2]).toContain('id:002');
            expect(content).toContain('For AI agents:');
        });

        it('should throw error if file does not exist', async () => {
            await expect(cleanTaskFile(TEST_FILE)).rejects.toThrow('File not found');
        });
    });

    describe('error handling', () => {
        beforeEach(async () => {
            await initTaskFile(TEST_FILE);
            await addTask(TEST_FILE, 'Test task');
        });

        it('should throw error when moving non-existent task', async () => {
            await expect(moveTask(TEST_FILE, '999', 'todo')).rejects.toThrow('Task 999 not found');
        });

        it('should throw error when marking non-existent task as done', async () => {
            await expect(markDone(TEST_FILE, '999')).rejects.toThrow('Task 999 not found');
        });

        it('should throw error when marking non-existent task as wontdo', async () => {
            await expect(markWontdo(TEST_FILE, '999')).rejects.toThrow('Task 999 not found');
        });

        it('should throw error when removing non-existent task', async () => {
            await expect(removeTask(TEST_FILE, '999')).rejects.toThrow('Task 999 not found');
        });
    });
});
